baseURL = "http://prems.stephanejacquet.fr"
languageCode = "en-us"
title = "English Class"

[module]
  [[module.imports]]
    path = "github.com/alex-shpak/hugo-book"
  
  [[module.mounts]]
    source = "assets"
    target = "assets"

# Book configuration
[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  BookTheme = 'cool-sage'

  # (Optional, default true) Controls table of contents visibility on right side of pages.
  BookToC = true

  # (Optional, default none) Set the path to a logo for the book.
  # BookLogo = 'logo.png'

  # (Optional, default docs) Specify section of content to render as menu
  BookSection = 'docs'

  # Enable search
  BookSearch = true

  # Enable responsive design features
  [params.BookServiceWorker]
    enable = false

# Enable HTML in markdown
[markup.goldmark.renderer]
  unsafe = true

# Ensure proper menu ordering
[menu]
  [[menu.after]]
    name = "Longman Dictionary"
    url = "https://www.ldoceonline.com/"
    weight = 10
