baseURL = "/"
languageCode = "en-us"
title = "Educational Website"
theme = "hugo-book"

# Book configuration
[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  BookTheme = 'light'

  # (Optional, default true) Controls table of contents visibility on right side of pages.
  BookToC = true

  # (Optional, default none) Set the path to a logo for the book.
  # BookLogo = 'logo.png'

  # (Optional, default docs) Specify section of content to render as menu
  BookSection = 'docs'

  # Enable search
  BookSearch = true

  # Enable responsive design features
  [params.BookServiceWorker]
    enable = true

# Enable HTML in markdown
[markup.goldmark.renderer]
  unsafe = true

# Add custom SCSS processing
[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"

# Ensure proper menu ordering
[menu]
  [[menu.after]]
    name = "GitHub"
    url = "https://github.com/alex-shpak/hugo-book"
    weight = 10
